In [1]:
import duckdb
import pandas as pd

In [14]:
sql_query = '''
select * from bronze_parking_vc

'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,violation_code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515
3,4,BUS PARKING IN LOWER MANHATTAN,115,115
4,5,BUS LANE VIOLATION,250,250
...,...,...,...,...
92,93,REMOVE/REPLACE FLAT TIRE,65,65
93,96,RAILROAD CROSSING,95,95
94,97,VACANT LOT,65,45
95,98,OBSTRUCTING DRIVEWAY,95,95
96,99,OTHER,105,105

In [18]:
sql_query = '''
show tables
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                      name
0         bronze_parking_v
1        bronze_parking_vc
2      gold_ticket_metrics
3    gold_vehicles_metrics
4  parking_violation_codes
5  parking_violations_2023
6         silver_v_tickets
7        silver_v_vehicles

In [9]:
sql_query_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes as
SELECT * from read_csv_auto('data/dof_parking_violation_codes.csv', normalize_names=TRUE)
'''

sql_query_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 as
SELECT * from read_csv_auto('data/parking_violations_issued_fiscal_year_2023_sample.csv', normalize_names=TRUE)
'''

In [10]:
with duckdb.connect('data/nyc_parking_violations.db') as con :
    con.sql(sql_query_1)
    con.sql(sql_query_2)

In [15]:
sql_query_3 = '''
CREATE OR REPLACE TABLE parking_violation_codes as
SELECT * from read_csv_auto('data/dof_parking_violation_codes.csv', normalize_names=TRUE)
'''

sql_query_4 = '''
CREATE OR REPLACE TABLE parking_violations_2023 as
SELECT * from read_csv_auto('data/parking_violations_issued_fiscal_year_2023_sample.csv', normalize_names=TRUE)

'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con :
    con.sql(sql_query_3)
    con.sql(sql_query_4)